### ISSUE TITLE
From where I should call $ ./gradlew extractStringsFromLayouts?

### ISSUE THREAD

**Issue by NehaKushwah993** [it-objects/android-string-extractor-plugin#8]

**Comment by kaushiknadig** [comment]
Hi.
Go to your project directory. Find the gradlew file.
Open a terminal if you are using Linux or command prompt if you are using windows, then run that command.
If by chance you get an error saying permission denied in Ubuntu, run this command
chmod +x gradlew.
This should start the string extraction process.

You can also run this from Android Studio itself. 

![Preview for Studio 1](https://user-images.githubusercontent.com/15876062/42934994-2928cfee-8b66-11e8-8a77-768cce2e676e.png)

![Preview for Studio 2](https://user-images.githubusercontent.com/15876062/42934993-28efddce-8b66-11e8-942f-292880cce633.png)
